[package]
name = "sqlx-example-sqlite-todos"
version = "0.1.0"
edition = "2018"
workspace = "../../../"

[dependencies]
anyhow = "1.0"
futures = "0.3"
sqlx = { path = "../../../", features = ["sqlite", "runtime-tokio-native-tls"] }
structopt = "0.3"
tokio = { workspace = true, optional = true }
